### PR TITLE
Payment method

### PR DESCRIPTION
**Pull request by XMRZombie**
Removed old docs and uploaded some payment methods

### CODE REVIEW

**Comment by woodser** [comment]
Thanks again, this is great.

I think the docs themselves are ready to merge into the repository, but they won't appear on https://haveno.exchange/ until they're added to the navigation section at https://github.com/haveno-dex/haveno-docs/blob/fae7635979a429974eb75a13584a9ae673e9a2c0/mkdocs.yml#L66.

Would you like to add them to this navigation section, or should I go ahead and merge the docs and they can be registered separately?

**Comment by XMRZombie** [comment]
I think that can be merged for the moment, i'm more focused on populating the documentation and indexing after

**Comment by woodser** [comment]
I notice that Zelle is missing as a payment method, in case you have that file as well by chance?

**Comment by XMRZombie** [comment]
I didnt made documentations for cashapp and zelle, just used "find & replace" tool to change "bisq" to "haveno" and "bitcoin" to "monero" in cloned bisq docs

**Pull request merged**
